### PR TITLE
fixes win32 detection

### LINKED ISSUE #36: recent fix borks win32 detection.
@ww-daniel-mora 3a1f45b does not correctly resolve whether or not I'm running on windows. I've always seen the vim.fn.has("win32") in examples, and that works on my machine, so I'm curious what prompted the change to vim.call("exists","win32") == 1 . It comes up false for me.

### PR DESCRIPTION
**Pull request by WillEhrendreich**
this works for me, the other method of detection didn't, for whatever reason. 

fixes #36

### CODE REVIEW

**Comment by WillEhrendreich** [comment]
i didnt get an error it simply returned false, so an or would not work here i don't believe.

File: lua/codeium/util.lua [hunk 1]
```diff
@@ -39,7 +39,8 @@ function M.get_newline(bufnr)
 end
 
 function M.has_win32()
-  return vim.call("exists", "*win32") == 1
+	return vim.fn.has("win32")
```
Comment (ww-daniel-mora) [inline lua/codeium/util.lua:42]: Unfortunately this always returns true. Per our discussion your vim.fn does not have this entry either so has function is not doing what you think it is doing.

Can you check the output of this call?
`:lua =vim.loop.os_uname().sysname`

Comment (jcdickinson) [reply lua/codeium/util.lua:42]: Oooooh fancy! `Linux` and `Darwin`. I will update the repo to os_uname tonight.
