### PR TITLE
fix for manager path issue.

### LINKED ISSUE #30: crashing on second instance of nvim
for whatever reason im getting it crashing if i ever open up a second neovim instance. 

after turning on trace logging i get this.

```
[codeium] [DEBUG 18:02:58] ...al/share/nvim-data/lazy/codeium.nvim/lua/codeium/api.lua:209: 46504: I0317 18:02:57.435801 46504 main.go:357] Starting language server manager with pid 46504
[codeium] [DEBUG 18:02:58] ...al/share/nvim-data/lazy/codeium.nvim/lua/codeium/api.lua:209: 46504: F0317 18:02:57.438467 46504 main.go:81] Failed to acquire manager lock file C:/Temp/nvim/codeium/manager/locks/manager.lock: <nil>
[codeium] [ERROR 18:02:58] ...share/nvim-data/lazy/codeium.nvim/lua/codeium/notify.lua:14: codeium server crashed:  {
[codeium]   code = 1
[codeium] }

```

I don't think this used to happen... and I'm not sure how it gets the lock in the first place or why it would not be able to get one a second time.

### PR DESCRIPTION
**Pull request by WillEhrendreich**
fixes #30

### CODE REVIEW

**Comment by WillEhrendreich** [comment]
added a bunch of windows related fixes too.

File: lua/codeium/api.lua [hunk 1]
```diff
@@ -177,11 +177,9 @@ function Server:new()
 
 		local manager_dir = config.manager_path
 		if not manager_dir then
-			if io.get_system_info().os == "windows" then
-				manager_dir = vim.fn.stdpath("cache") .. "/codeium/manager"
+			manager_dir = io.tempdir("codeium/manager")
+			if vim.fn.has("win32") == 1 then
```
Comment (jcdickinson) [inline lua/codeium/api.lua:181]: It's safe to mkdir with `p` if the directory exists, so you can remove this `if` check.

File: lua/codeium/io.lua [hunk 2]
```diff
@@ -304,37 +299,48 @@ function M.job(cmd)
...
-		end
-	else
+	if vim.fn.has("win32") then
 		M.job({
-			"gzip",
-			"-d",
+			"powershell.exe",
+			"-noprofile",
+			"-command",
+			"\"Expand-Archive -Path '",
```
Comment (jcdickinson) [inline lua/codeium/io.lua:326]: I would expect that it would require something along the lines of:

```lua
// ...
"-command",
"Expand-Archive -Path '" .. path .. "' -DestinationPath '.'",
// ...
```

`job` doesn't concatenate args, parsing native APIs take args as an array, even on Windows, and the shell is responsible for parsing them out to an array. That being said nvim could be doing some nasty hack with `cmd.exe` internally.

**Review by jcdickinson — APPROVED** [review]
lgtm. Feedback is optional.

File: lua/codeium/io.lua (hunk 2 above)
Comment (WillEhrendreich) [reply lua/codeium/io.lua:326]: I have no idea if nvim is doing anything strange. I decided to go with powershell, though it could have been cmd just as easily. It seems to not blow up, so I went with it, it doesn't come from an informed opinion. I'm pretty unfamiliar with shells across the board, have only written a couple of powershell scripts and and BAT files over the years, so as far as the details regarding how it does or does not take args and what it does with them I'm just taking guesses and asking some AI to throw me a bone. I think I just saw that the job call with gzip took the args like this, so I just tried to make it similar. If you feel like it's better another way I'll gladly do it, I defer to anyone else who knows what their doing, lol.

File: lua/codeium/api.lua (hunk 1 above)
Comment (WillEhrendreich) [reply lua/codeium/api.lua:181]: Ah ok. I didn't know that thanks!

**Comment by jcdickinson** [comment]
If it works, I am happy. Merged. Is everything working on Windows now?
